{
  "image": {
    "repository": "dddd",
    "tag": "latest",
    "pullPolicy": "IfNotPresent"
  },
  "nameOverride": "",
  "fullnameOverride": "",
  "serviceAccount": {
    "create": true,
    "name": ""
  },
  "podAnnotations": {},
  "podSecurityContext": {
    "runAsNonRoot": true,
    "runAsUser": 1000
  },
  "securityContext": {},
  "service": {
    "type": "ClusterIP",
    "port": 80
  },
  "ingress": {
    "enabled": false,
    "className": "nginx",
    "annotations": {},
    "hosts": [
      {
        "host": "",
        "paths": [
          {
            "path": "/",
            "pathType": "Prefix"
          }
        ]
      }
    ]
  },
  "resources": {
    "limits": {
      "cpu": "0.5",
      "memory": "512Mi"
    },
    "requests": {
      "cpu": "0.5",
      "memory": "512Mi"
    }
  },
  "autoscaling": {
    "enabled": false,
    "minReplicas": 1,
    "maxReplicas": 10,
    "targetCPUUtilization": 80
  },
  "nodeSelector": {},
  "tolerations": [],
  "affinity": {},
  "persistence": []
}