name: 01-Basic Terraform Script
on:
  workflow_dispatch: 
    inputs:
      actions:
        description: 'Terraform Action'
        required: true
        type: choice
        options:
          - plan
          - apply
          - destroy
        default: plan
      
jobs:
  terraform:
    name: 'Terraform Infrastructure'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Terraform_GKE_Project/01-Basics-Terraform
    
    # Add these permissions to ensure proper access
    permissions:
      contents: read
      pull-requests: write
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Updated to latest version
        with:
          path: 'Terraform_GKE_Project'
       
      
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2  # Updated to latest version
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          install_components: 'beta'
      
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2  # Updated to latest version
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
     
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3  # Updated to latest version
        with:
          terraform_wrapper: false  # Recommended for better output
      
      - name: Terraform Initialize
        run: terraform init 
      #       # \-backend-config="bucket=${{ secrets.TERRAFORM_STATE_BUCKET }}" \
      #       # -backend-config="prefix=gke-cluster"
      
      - name: Terraform Validate          
        run: terraform validate
      
      - name: Terraform Plan
        if: github.event.inputs.actions == 'plan'
        run: |
          terraform plan -out=tfplan
          terraform show -no-color tfplan > plan_output.txt
          cat plan_output.txt
      
      - name: Terraform Apply
        if: github.event.inputs.actions == 'apply'
        run: |
          terraform apply -auto-approve
      
      - name: Terraform Destroy
        if: github.event.inputs.actions == 'destroy'
        run: |
          terraform destroy -auto-approve
      
      # Optional: Upload plan output as artifact
      - name: Upload Plan Output
        if: github.event.inputs.actions == 'plan'
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: plan_output.txt
          retention-days: 5