name: 04-best practice

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      actions:
        description: 'Terraform Action'
        required: true
        type: choice
        options:
          - plan
          - apply
          - destroy
        default: plan

jobs:
  terraform:
    name: 'Terraform Infrastructure'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Terraform_GKE_Project/standard-gke-infra

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          path: 'Terraform_GKE_Project'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          install_components: 'beta'

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Check Terraform Initialization
        id: terraform_init_check
        run: |
          if [ -d ".terraform" ]; then
            echo "::set-output name=initialized::true"
          else
            echo "::set-output name=initialized::false"
          fi

      - name: Terraform Validate
        if: steps.terraform_init_check.outputs.initialized == 'true'
        run: terraform validate

      - name: Terraform Plan
        if: github.event.inputs.actions == 'plan' && steps.tf-files-changed.outputs.changed == 'true' && steps.terraform_init_check.outputs.initialized == 'true'
        run: |
          terraform plan -out=tfplan
          terraform show -no-color tfplan > plan_output.txt
          cat plan_output.txt

      # Additional Terraform steps (Apply, Destroy) ...