name: 05-Private GKE Cluster Creation (old)
on:
  workflow_dispatch: 
    inputs:
      actions:
        description: 'Terraform Action'
        required: true
        type: choice
        options:
          - plan
          - apply
          - destroy
        default: plan
      
jobs:
  terraform:
    name: '01-private_gke_cluster'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Terraform_GKE_Project/03-gke_private_cluster
    
    # Add these permissions to ensure proper access
    permissions:
      contents: read
      pull-requests: write
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          path: 'Terraform_GKE_Project'
      
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          install_components: 'beta'
      
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
     
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
      
      - name: Terraform Initialize
       
        run: terraform init \
            # -backend-config="bucket=${{ secrets.TERRAFORM_STATE_BUCKET }}" \
            # -backend-config="prefix=gke-cluster"
      
      - name: Terraform Validate   
        run: terraform validate
      
      - name: Terraform Plan
        if: github.event.inputs.actions == 'plan'
        run: |
          terraform plan -out=tfplan
          terraform show -no-color tfplan > plan_output.txt
          cat plan_output.txt
      
      - name: Terraform Apply
        if: github.event.inputs.actions == 'apply'
        run: |
          terraform apply -auto-approve
      
      - name: Terraform Destroy
        if: github.event.inputs.actions == 'destroy'
        run: |
          terraform destroy -auto-approve
      
      # Optional: Upload plan output as artifact
      - name: Upload Plan Output
        if: github.event.inputs.actions == 'plan'
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: Terraform_GKE_Project/standard-gke-infra/plan_output.txt
          retention-days: 5